FROM python:3.8
RUN mkdir /code
WORKDIR /code
ADD requirements_client.txt /code
ADD requirements_dbwriter.txt /code
ADD requirements_develop.txt /code
RUN pip install -r requirements_develop.txt
ADD ./code /code
